//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletAPP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbBiletEntities : DbContext
    {
        public dbBiletEntities()
            : base("name=dbBiletEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbBiletler> tbBiletler { get; set; }
        public virtual DbSet<tbKullanicilar> tbKullanicilar { get; set; }
        public virtual DbSet<tbOtobusler> tbOtobusler { get; set; }
        public virtual DbSet<tbSeferler> tbSeferler { get; set; }
        public virtual DbSet<tbSubeler> tbSubeler { get; set; }
        public virtual DbSet<tbSubeler2> tbSubeler2 { get; set; }
    }
}
