//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKullanicilar
    {
        public string kullanici_adi { get; set; }
        public string kullanici_sifresi { get; set; }
        public string kullanici_ad_soyad { get; set; }
        public string kullanici_mail { get; set; }
        public string kullanici_tel { get; set; }
        public string kullanici_adres { get; set; }
        public Nullable<bool> kullanici_admin { get; set; }
    }
}
