//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOtobusler
    {
        public string plaka { get; set; }
        public string otobus_marka { get; set; }
        public string otobus_model { get; set; }
    }
}
