//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSeferler
    {
        public int sefer_id { get; set; }
        public Nullable<System.DateTime> sefer_tarih { get; set; }
        public Nullable<System.TimeSpan> sefer_saat { get; set; }
        public Nullable<int> sefer_baslangic_sube { get; set; }
        public Nullable<int> sefer_bitis_sube { get; set; }
        public Nullable<double> fiyat { get; set; }
        public string plaka { get; set; }
    
        public virtual tbSubeler2 tbSubeler2 { get; set; }
    }
}
